### ISSUE TITLE
Errors on initial build

### ISSUE THREAD

**Issue by leegee** [inadarei/nodebootstrap#27]
Hi
Looks like a very useful project, thanks in advance.
On my initial build and run I copied and pasted the output from the installation command:
```console
======================= Installation Completed! ===================
You can now run your newly minted Node app by executing:
  > cd asset-review
  > ./bin/dev_starth.sh
```
There is a typo in the output's last line.
There is also a missing dependency when running `./bin/dev_start.sh`:
```console
module.js:340
    throw err;
          ^
Error: Cannot find module 'nodebootstrap-clustering'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.exports.setup (/Users/lee/src/www/mark-review/asset-review/node_modules/nodebootstrap-server/app.js:25:5)
    at Object.<anonymous> (/Users/lee/src/www/mark-review/asset-review/server.js:1:95)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Program node ....../server.js exited with code 8
```

**Comment by inadarei** [comment]
Thanks. There's a PR that should fix this problem and couple others: https://github.com/inadarei/nodebootstrap/pull/25 just needs some testing. Will try to get to it ASAP.

**Comment by inadarei** [comment]
This shouldn't be a problem anymore
