### ISSUE TITLE
Error shows up during project build on Windows PC

### ISSUE THREAD

**Issue by kanishka28** [inadarei/nodebootstrap#36]
Hi,

I am using the NodeBootstrap composition v3.0.2 (https://github.com/inadarei/nodebootstrap) on my Windows PC (Window 7, 64-bit).

It installs correctly through NPM. But when I try to create a project (nodebootstrap build hello), it shows up the following error:
Executing installation of dependencies. This may take several minutes.
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at Object.exports.execFile (child_process.js:689:15)
    at c:\Users\pp\AppData\Roaming\npm\node_modules\nodebootstrap\bin\nodebootst
rap:81:32
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)

Can you please help me with this? I am unable to find a solution to this error.

Node version: 0.12.4
NPM version: 2.10.1

Screenshot of the error is enclosed for your reference.

Looking forward to a quick response.

Thanks,
Kanishka

![error](https://cloud.githubusercontent.com/assets/12987320/8271526/c2c969da-17d1-11e5-9264-8c63855fe17a.PNG)

**Comment by inadarei** [comment]
NodeBootstrap build tool is not supported on bare Windows since it requires bash. You can try using Cygwin, in case it works.
