### ISSUE TITLE
while building the hello project throws error 

### ISSUE THREAD

**Issue by manishupadhyay** [inadarei/nodebootstrap#37]
Please find the complete error trace below.

child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at c:\Users\Manish.Upadhyay\AppData\Roaming\npm\node_modules\nodebootstrap\bin\nodebootstrap:81:32
    at ChildProcess.exithandler (child_process.js:735:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)

**Comment by inadarei** [comment]
Unofrtunately, current version of NodeBootstrap build tool is not supported on bare Windows since it requires bash. You can try using Cygwin, in case it works.

I will expect a pull request if somebody wants to add support for Windows, but I have no immediate plans for supporting Windows, in the near future.
