### ISSUE TITLE
build Error - Firewall ?

### ISSUE THREAD

**Issue by paulcull** [inadarei/nodebootstrap#38]
Hi,

I'm getting a error running the build. 

```
$ /opt/app/cloudstack/node/node-v0.12.5-linux-x64/bin/nodebootstrap build hello
Building new project under: hello
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND github.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

This is in a corporate environment with a proxy in place. running redhat.

Thanks

**Comment by inadarei** [comment]
Most probably it is a firewall issue. Did you have a chance to run it outside the firewall?

**Comment by paulcull** [comment]
Hi - can be closed. Needs the HTTP(S)_PROXY setting as well as the proxy in .npmrc.

thank

**Comment by inadarei** [comment]
Cool. Thanks for following up and posting the solution, Paul.

**Comment by sochix** [comment]
Hi! I added proxy to .npmrc but still get an error
```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```
