### ISSUE TITLE
What port does forever (start.sh) run the server on?

### ISSUE THREAD

**Issue by nikkwong** [inadarei/nodebootstrap#49]
I can't seem to access my app in a web browser when running the app in production mode.

Thanks!

**Comment by inadarei** [comment]
Are you using Docker version or straight-up?

**Comment by nikkwong** [comment]
Straight up :-)

**Comment by inadarei** [comment]
Can you check the logs, please? What's in the logs?

**Comment by nikkwong** [comment]
Thanks! I'm getting: 

````
TypeError: Cannot read property 'domain' of undefined
    at Domain.add (domain.js:171:27)
    at errorHandler (/home/ec2-user/deploy/node_modules/error-handler/errorHandler.js:32:7)
    at /home/ec2-user/deploy/server.js:28:42
    at Object.exports.setup (/home/ec2-user/deploy/node_modules/nodebootstrap-server/app.js:41:3)
    at Object.<anonymous> (/home/ec2-user/deploy/server.js:17:8)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
domain.js:171
  if (this._disposed || ee.domain === this)
                          ^
````

**Comment by inadarei** [comment]
@nikkwong,

were you able to find out what the issue was with this one?

**Comment by nikkwong** [comment]
I don't remember unfortunately. Hopefully won't run into it again :-)
